permalink: /:year/:month/:title.html
markdown: rdiscount
exclude: [TODO, config.ru, vendor, Gemfile, Gemfile.lock, README.md, .ruby-version, scripts]

url: cookbook.garno.me
google_analytics_id: 'UA-43959293-4'
